export enum ActionTypes {
  SET_COW = 'SET_COW',
  SET_PRICE = 'SET_PRICE',
  SET_INSERT_NEW_COW = 'SET_INSERT_NEW_COW',
  SET_NEW_COW = 'SET_NEW_COW',
  SET_REPRODUCTION_RECORD = 'SET_REPRODUCTION_RECORD',
  SET_REPRODUCTORES_LIST = 'SET_REPRODUCTORES_LIST',
}
