export enum CalendarActionsEnum {
  GET_DAILY_MILK = 'GET_DAILY_MILK',
  GET_DRUGS_LIST = 'GET_DRUGS_LIST',
  GET_INSEMINACIONES_MONTAS = 'GET_INSEMINACIONES_MONTAS',
  GET_PREÑEZ_MONTA = 'GET_PREÑEZ_MONTA',
}
