export enum ICowKeys {
  idVaca = 'idVaca',
  nombre = 'nombre',
  sexo = 'sexo',
  numeroDeArete = 'numeroDeArete',
  fechaDeNacimiento = 'fechaDeNacimiento',
  raza = 'raza',
  diasGestación = 'diasGestación',
  pesoNacimiento = 'pesoNacimiento',
  estadoProductivo = 'estadoProductivo',
  estadoReproductivo = 'estadoReproductivo',
  tipoAborto = 'tipoAborto',
  categoria = 'categoria',
  valorDelBovino = 'valorDelBovino',
  nombreDeMadre = 'nombreDeMadre',
  numeroAreteMadre = 'numeroAreteMadre',
  nombreDePadre = 'nombreDePadre',
  numeroAretePadre = 'numeroAretePadre',
  fechaDestete = 'fechaDestete',
  pesoAlDestete = 'pesoAlDestete',
  pesoActual = 'pesoActual',
  numeroDeAbortos = 'numeroDeAbortos',
  diasDeGestacion = 'diasDeGestacion',
  fechaDeParto = 'fechaDeParto',
  numeroDeCrias = 'numeroDeCrias',
  imagenPath = 'imagenPath',
}
