import {ICow} from '../interfaces/CowInterface';

export const vaca0: ICow = {
  idVaca: '007xD',
  nombre: 'Noname',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  diasGestación: 283,
  pesoNacimiento: 123,
  estadoProductivo: 'Descarte',
  estadoReproductivo: 'Aborto',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
  imagenPath: 'https://i.imgur.com/FQ8Yzq4.png',
};

export const vaca1: ICow = {
  idVaca: '123',
  nombre: 'Dana',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  diasGestación: 283,
  pesoNacimiento: 123,
  estadoProductivo: 'Descarte',
  estadoReproductivo: 'Aborto',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
  imagenPath: 'https://i.imgur.com/FQ8Yzq4.png',
};

export const vaca2: ICow = {
  idVaca: '123',
  nombre: 'Hella',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  diasGestación: 283,
  pesoNacimiento: 123,
  estadoProductivo: 'Novilla no lactante',
  estadoReproductivo: 'Vacia',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
  imagenPath: 'https://i.imgur.com/nFhPmoo.png',
};

export const vaca3: ICow = {
  idVaca: '1234',
  nombre: 'ADELINA',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  diasGestación: 283,
  pesoNacimiento: 123,
  estadoProductivo: 'Vaca con alta producción',
  estadoReproductivo: 'Preñada',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
  imagenPath: 'https://i.imgur.com/nFhPmoo.png',
};
export const vaca4: ICow = {
  idVaca: '1235',
  nombre: 'VANESSA',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  diasGestación: 283,
  pesoNacimiento: 123,
  estadoProductivo: 'Vaca con media producción',
  estadoReproductivo: 'Precentina',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
  imagenPath: 'https://i.imgur.com/nFhPmoo.png',
};
export const vaca5: ICow = {
  idVaca: '1236',
  nombre: 'CRISTINA',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  diasGestación: 283,
  pesoNacimiento: 123,
  estadoProductivo: 'Vaca con baja producción',
  estadoReproductivo: 'Seca',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
  imagenPath: 'https://i.imgur.com/nFhPmoo.png',
};

export const vaca6: ICow = {
  idVaca: '1237',
  nombre: 'CARMINA',
  sexo: 'Hembra',
  diasGestación: 283,
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  pesoNacimiento: 123,
  estadoProductivo: 'Reproductor',
  estadoReproductivo: 'Preñada',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
  imagenPath: 'https://i.imgur.com/nFhPmoo.png',
};

export const vacas: ICow[] = [vaca0, vaca1, vaca2, vaca3, vaca4, vaca5, vaca6];
