import {ICow} from '../interfaces/CowInterface';

export const vaca1: ICow = {
  idVaca: '123',
  nombre: 'Dana',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  pesoNacimiento: 123,
  estadoProductivo: 'Descarte',
  estadoReproductivo: 'Aborto',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
};

export const vaca2: ICow = {
  idVaca: '123',
  nombre: 'Hella',
  sexo: 'Hembra',
  numeroDeArete: '546',
  fechaDeNacimiento: 12333123,
  raza: 'holstein',
  pesoNacimiento: 123,
  estadoProductivo: 'Descarte',
  estadoReproductivo: 'Aborto',
  tipoAborto: 'Aborto Normal',
  categoria: 'Vaca seca',
  valorDelBovino: 123,
  nombreDeMadre: 'Elina',
  numeroAreteMadre: '1233',
  nombreDePadre: 'Papa',
  numeroAretePadre: '098',
  fechaDestete: 123213123,
  pesoAlDestete: 32.2,
  pesoActual: 40,
  numeroDeAbortos: 0,
  diasDeGestacion: 0,
  fechaDeParto: 0,
  numeroDeCrias: 0,
};

export const vacas: ICow[] = [vaca1, vaca2];
